export default {
    SERVER_ERROR: 'SERVER_ERROR',
    DISPOSE_SERVER_ERROR: 'DISPOSE_SERVER_ERROR',
    LOAD_DATA: 'LOAD_DATA',
    LOAD_DATA_SUCCESS: 'LOAD_DATA_SUCCESS',
    LOAD_DATA_FAILURE: 'LOAD_DATA_FAILURE',
    SET_FILTER: 'SET_FILTER',
    CENTER_MAP: 'CENTER_MAP',
    ZOOM_MAP: 'ZOOM_MAP',
}